### PR TITLE
 Fix npm build bugs for bash scripts on windows environments

### LINKED ISSUE #958: npm run build:fonts is not working
## Description

The command npm run build:fonts is not working on my local computer.
npm run bild fonts error

A link of the snapshot of the error has been attached to this message.

### LINKED ISSUE #959: Broken package links on the Readme
## Description
We Noticed that links on the package sections of the Readme are broken (this returns a 404 error when clicked on) 

## Expectation
The links are expected to link to the individual package pages.

## Screenshots
image

### PR DESCRIPTION
**Pull request by MuluhGodson**
## Fixes

Fixes #958  by @emmaxy07
Fixes #959  by @Akpjunior94

## Description
Most of these commands run without issues on Linux but in windows due to path issues, these commands were breaking. This fix corrects the path issues making these scripts do their functions on both Linux and windows development environments.
Another issue I found was how windows handles linebreaks (LF or CRLF) for its bash environment. This causes the scripts to break during execution but a simple fix will be to add the fix option to the script command. Example instead of running `npm run build:fonts` do `npm run build:fonts --fix` and the error will be auto-resolved. I have already documented this in `README.md` file.

This fix will enable our windows developers to be able to compile successfully.
The following commands should work:
[x] `npm run serve`
[x] `npm run build:fonts` or `npm run build:fonts --fix` for windows devs
[x] `npm run build:vocabulary` or `npm run build:vocabulary --fix` 
[x] `npm run build:vue-vocabulary` or `npm run build:vue-vocabulary --fix`
[x] `npm run lint`

## Tests
Those who faced this issue, can test this features so we can be sure it works in their setups. Run the various build commands:
```bash
npm run build:fonts --fix
npm run build:vocabulary --fix
npm run build:vue-vocabulary --fix
```

### Problem
image

### Solution
image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Akpjunior94** [comment]
Great work @MuluhGodson

**Comment by emmaxy07** [comment]
Nice one @MuluhGodson

File: scripts/build_fonts.sh [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
 
 # Run build
-vue-cli-service build --target lib --name fonts --dest ./dist/fonts --entry ./src/fonts.js
+./node_modules/.bin/vue-cli-service build --target lib --name fonts --dest ./dist/fonts --entry ./src/fonts.js
 
 echo -n "Copying meta files..."
 cp README.md dist/fonts
 cp LICENSE dist/fonts
-cp packages/fonts.json dist/fonts/package.json
+#cp packages/fonts.json dist/fonts/package.json
```
Comment (brylie) [inline scripts/build_fonts.sh]: I think we should restore this `package.json` since it has project metadata.

File: README.md [hunk 2]
```diff
@@ -89,6 +89,12 @@ For example, to build the `fonts` package, run the following commands:
 npm install --legacy-peer-deps
 npm run build:fonts
 ```
+
+Sometimes, on windows environments you may get an error about linebreaks, fix that by running the command as
+
+```bash
+npm run build:fonts --fix
+```
```
Comment (brylie) [inline README.md:97]: This should be moved to a "Build and publish" section of the guide since it is related to building packages for publication.

File: scripts/build_vocabulary.sh [hunk 3]
```diff
@@ -1,12 +1,12 @@
...
 
 # Run build
-vue-cli-service build --target lib --name vocabulary --dest ./dist/vocabulary --entry ./src/vocabulary.js
+./node_modules/.bin/vue-cli-service build --target lib --name vocabulary --dest ./dist/vocabulary --entry ./src/vocabulary.js
 
 echo -n "Copying meta files..."
 cp README.md dist/vocabulary
 cp LICENSE dist/vocabulary
-cp packages/vocabulary.json dist/vocabulary/package.json
+#cp packages/vocabulary.json dist/vocabulary/package.json
```
Comment (brylie) [inline scripts/build_vocabulary.sh]: Let's restore this file rather than commenting out the line.

File: scripts/build_vue_vocabulary.sh [hunk 4]
```diff
@@ -1,12 +1,12 @@
...
 
 # Run build
-vue-cli-service build --target lib --name vue-vocabulary --dest ./dist/vue-vocabulary --entry ./src/vue_vocabulary.js
+./node_modules/.bin/vue-cli-service build --target lib --name vue-vocabulary --dest ./dist/vue-vocabulary --entry ./src/vue_vocabulary.js
 
 echo -n "Copying meta files..."
 cp README.md dist/vue-vocabulary
 cp LICENSE dist/vue-vocabulary
-cp packages/vue-vocabulary.json dist/vue-vocabulary/package.json
+#cp packages/vue-vocabulary.json dist/vue-vocabulary/package.json
```
Comment (brylie) [inline scripts/build_vue_vocabulary.sh]: Let's restore this file rather than commenting out the line.

**Review by brylie — CHANGES_REQUESTED** [review]

File: scripts/build_fonts.sh (hunk 1 above)
Comment (MuluhGodson) [reply scripts/build_fonts.sh]: Okay, Let me restore the packages/fonts.json and run some more test

Comment (MuluhGodson) [reply scripts/build_fonts.sh]: @brylie I restored the folder but the file it's supposed to copy `fonts.json` doesn't exist in that folder. Looking at the configuration in the `package.json` file of that packages folder suggest that it used to be compiled using webpack

File: README.md (hunk 2 above)
Comment (MuluhGodson) [reply README.md:97]: Okay got it.

Comment (brylie) [reply README.md:97]: I realize this project is missing some key context. Thank you for helping us to improve the documentation and development process. :-)

Comment (MuluhGodson) [reply README.md:97]: The heading for this section is ##Building the packages

Comment (brylie) [reply README.md:97]: Yes, with a space after the hash marks "## Building the packages"

Comment (brylie) [reply README.md:97]: Ah my bad. Sorry. I didn't notice the collapsed code. Resolving this conversation.

File: scripts/build_fonts.sh (hunk 1 above)
Comment (brylie) [reply scripts/build_fonts.sh]: OK, let's just set up some default package.json files with `name` and `version` fields for now.

<details>

<summary>example fonts/package.json</summary>

```json
{
    "name": "cc-vocabulary-fonts",
    "version": "1.0.0"
}
```

</details>

Comment (MuluhGodson) [reply scripts/build_fonts.sh]: This will be the best option

Comment (brylie) [reply scripts/build_fonts.sh]: The version number should be our latest release:

image

Comment (MuluhGodson) [reply scripts/build_fonts.sh]: @brylie I have done this in the latest commit

File: scripts/build_fonts.sh [hunk 5]
```diff
@@ -6,7 +6,7 @@
 echo -n "Copying meta files..."
 cp README.md dist/fonts
 cp LICENSE dist/fonts
-#cp packages/fonts.json dist/fonts/package.json
+cp packages/fonts/package.json dist/fonts/package.json
```
Comment (brylie) [inline scripts/build_fonts.sh:9]: This doesn't have the leading `./`. If it works without the `./` we should remove `./` from the other files. Otherwise, add `./` for consistency.

**Review by brylie — CHANGES_REQUESTED** [review]

File: scripts/build_fonts.sh (hunk 5 above)
Comment (MuluhGodson) [reply scripts/build_fonts.sh:9]: Oh I missed that. I think preferably it should be removed since it works without.

**Review by brylie — APPROVED** [review]

File: .github/workflows/cd-fonts.yml [hunk 6]
```diff
@@ -28,7 +28,7 @@ jobs:
         run: npm install --no-audit
 
       - name: Publish package
-        run: bash deploy.sh
+        run: bash scripts/build_fonts.sh
```
Comment (brylie) [inline .github/workflows/cd-fonts.yml]: We actually need to restore the `deploy.sh`, since building the package is only one step in the deployment process.

File: .github/workflows/cd-vocabulary.yml [hunk 7]
```diff
@@ -28,7 +28,7 @@ jobs:
         run: npm install --no-audit
 
       - name: Publish package
-        run: bash deploy.sh
+        run: bash scripts/build_vocabulary.sh
```
Comment (brylie) [inline .github/workflows/cd-vocabulary.yml]: We actually need to restore the `deploy.sh`, since building the package is only one step in the deployment process.

File: .github/workflows/cd-vue.yml [hunk 8]
```diff
@@ -27,6 +27,6 @@ jobs:
         run: npm install --no-audit
 
       - name: Publish package
-        run: bash deploy.sh
+        run: bash scripts/build_vue_vocabulary.sh
```
Comment (brylie) [inline .github/workflows/cd-vue.yml]: We actually need to restore the `deploy.sh`, since building the package is only one step in the deployment process.

**Comment by MuluhGodson** [comment]
The most recent commit here should fix #961 #962 #963 #964

File: .github/workflows/cd-fonts.yml (hunk 6 above)
Comment (brylie) [reply .github/workflows/cd-fonts.yml]: https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/fonts/deploy.sh

File: .github/workflows/cd-vocabulary.yml (hunk 7 above)
Comment (brylie) [reply .github/workflows/cd-vocabulary.yml]: https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vocabulary/deploy.sh

File: .github/workflows/cd-vue.yml (hunk 8 above)
Comment (brylie) [reply .github/workflows/cd-vue.yml]: https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vue-vocabulary/deploy.sh

**Review by brylie — CHANGES_REQUESTED** [review]

**Comment by brylie** [comment]
@MuluhGodson, let's not add too much more in this pull request. Subsequent issues can be resolved with distinct pull requests.

**Comment by brylie** [comment]
> The most recent commit here should fix #961 #962 #963 #964

Go ahead and use the GitHub keywords to link this pull request to those issues.

When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

File: .github/workflows/cd-vue.yml (hunk 8 above)
Comment (MuluhGodson) [reply .github/workflows/cd-vue.yml]: Okay I see. Yeah it makes more sense to have a different deploy script

**Comment by brylie** [comment]
For clarification, the scope of this pull request should remain "Fix npm build bugs for bash scripts on windows environments." Let's continue other tasks in separate pull requests.

**Comment by MuluhGodson** [comment]
closes #958 
closes #959

**Comment by brylie** [comment]
Add those "Closes #..." messages to the pull request description.

**Comment by brylie** [comment]
@MuluhGodson, let's finish this pull request before starting another. There are a few out-of-scope changes in this pull request. Would you please revert changes related to #958 and #959 by removing/reverting the code and committing those changes?

File: .github/workflows/cd-fonts.yml (hunk 6 above)
Comment (brylie) [reply .github/workflows/cd-fonts.yml]: Revert this change
```suggestion
        run: bash deploy.sh
```

File: .github/workflows/cd-vocabulary.yml [hunk 9]
```diff
@@ -12,7 +12,7 @@ jobs:
   deploy_npm:
     defaults:
       run:
-        working-directory: "packages/vocabulary"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/cd-vocabulary.yml]: Revert this change
```suggestion
        working-directory: "packages/vocabulary"
```

File: .github/workflows/cd-vocabulary.yml (hunk 7 above)
Comment (brylie) [reply .github/workflows/cd-vocabulary.yml]: Revert this change
```suggestion
        run: bash deploy.sh
```

File: .github/workflows/cd-vue.yml [hunk 10]
```diff
@@ -11,7 +11,7 @@ jobs:
   deploy_npm:
     defaults:
       run:
-        working-directory: "packages/vue-vocabulary"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/cd-vue.yml]: Revert this change
```suggestion
        working-directory: "packages/vue-vocabulary"
```

File: .github/workflows/cd-vue.yml (hunk 8 above)
Comment (brylie) [reply .github/workflows/cd-vue.yml]: Revert this change
```suggestion
        run: bash deploy.sh
```

File: .github/workflows/ci-fonts.yml [hunk 11]
```diff
@@ -3,12 +3,12 @@ name: CI for fonts package
 on:
   push:
     paths:
-      - "packages/fonts/**"
+      - "scripts/**"
```
Comment (brylie) [inline .github/workflows/ci-fonts.yml]: Revert
```suggestion
      - "packages/fonts/**"
```

File: .github/workflows/ci-fonts.yml [hunk 12]
```diff
@@ -3,12 +3,12 @@ name: CI for fonts package
...
     branches:
       - main
   pull_request:
     paths:
-      - "packages/fonts/**"
+      - "scripts/**"
```
Comment (brylie) [inline .github/workflows/ci-fonts.yml]: Revert
```suggestion
      - "packages/fonts/**"
```

File: .github/workflows/ci-fonts.yml [hunk 13]
```diff
@@ -21,7 +21,7 @@ jobs:
     name: Setup
     defaults:
       run:
-        working-directory: "packages/fonts"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/ci-fonts.yml]: Revert
```suggestion
        working-directory: "packages/fonts"
```

File: .github/workflows/ci-fonts.yml [hunk 14]
```diff
@@ -46,7 +46,7 @@ jobs:
     name: Lint
     defaults:
       run:
-        working-directory: "packages/fonts"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/ci-fonts.yml]: Revert
```suggestion
        working-directory: "packages/fonts"
```

File: .github/workflows/ci-fonts.yml [hunk 15]
```diff
@@ -71,40 +71,11 @@ jobs:
...
-        with:
-          path: ~/.npm # npm caches files in ~/.npm
-          key: node-${{ hashFiles('**/package-lock.json') }}
-
-      - name: Install dependencies
-        run: npm install --prefer-offline --no-audit
-
-      - name: Run tests
-        run: npm run test:unit
-
```
Comment (brylie) [inline .github/workflows/ci-fonts.yml]: Revert

File: .github/workflows/ci-fonts.yml [hunk 16]
```diff
@@ -71,40 +71,11 @@ jobs:
...
   build:
     name: Build
     defaults:
       run:
-        working-directory: "packages/fonts"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/ci-fonts.yml]: Revert
```suggestion
        working-directory: "packages/fonts"
```

File: .github/workflows/ci-fonts.yml [hunk 17]
```diff
@@ -127,4 +98,4 @@ jobs:
         run: npm install --prefer-offline --no-audit
 
       - name: Run build
-        run: npm run build
+        run: npm run build:fonts
```
Comment (brylie) [inline .github/workflows/ci-fonts.yml]: Revert
```suggestion
        run: npm run build
```

File: .github/workflows/ci-vocabulary.yml [hunk 18]
```diff
@@ -3,12 +3,12 @@ name: CI for vocabulary package
 on:
   push:
     paths:
-      - "packages/vocabulary/**"
+      - "scripts/**"
```
Comment (brylie) [inline .github/workflows/ci-vocabulary.yml]: Revert
```suggestion
      - "packages/vocabulary/**"
```

File: .github/workflows/ci-vocabulary.yml [hunk 19]
```diff
@@ -3,12 +3,12 @@ name: CI for vocabulary package
...
     branches:
       - main
   pull_request:
     paths:
-      - "packages/vocabulary/**"
+      - "scripts/**"
```
Comment (brylie) [inline .github/workflows/ci-vocabulary.yml]: Revert
```suggestion
      - "packages/vocabulary/**"
```

File: .github/workflows/ci-vocabulary.yml [hunk 20]
```diff
@@ -21,7 +21,7 @@ jobs:
     name: Setup
     defaults:
       run:
-        working-directory: "packages/vocabulary"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/ci-vocabulary.yml]: Revert
```suggestion
        working-directory: "packages/vocabulary"
```

File: .github/workflows/ci-vocabulary.yml [hunk 21]
```diff
@@ -47,7 +47,7 @@ jobs:
     name: Lint
     defaults:
       run:
-        working-directory: "packages/vocabulary"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/ci-vocabulary.yml]: Revert
```suggestion
        working-directory: "packages/vocabulary"
```

File: .github/workflows/ci-vocabulary.yml [hunk 22]
```diff
@@ -72,40 +72,11 @@ jobs:
...
-        with:
-          path: ~/.npm # npm caches files in ~/.npm
-          key: node-${{ hashFiles('**/package-lock.json') }}
-
-      - name: Install dependencies
-        run: npm install --prefer-offline --no-audit
-
-      - name: Run tests
-        run: npm run test:unit
-
```
Comment (brylie) [inline .github/workflows/ci-vocabulary.yml]: Revert

File: .github/workflows/ci-vocabulary.yml [hunk 23]
```diff
@@ -72,40 +72,11 @@ jobs:
...
   build:
     name: Build
     defaults:
       run:
-        working-directory: "packages/vocabulary"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/ci-vocabulary.yml]: Revert
```suggestion
        working-directory: "packages/vocabulary"
```

File: .github/workflows/ci-vocabulary.yml [hunk 24]
```diff
@@ -135,4 +106,4 @@ jobs:
         run: npm install --prefer-offline --no-audit
 
       - name: Run build
-        run: npm run build
+        run: npm run build:vocabulary
```
Comment (brylie) [inline .github/workflows/ci-vocabulary.yml]: Revert
```suggestion
        run: npm run build
```

File: .github/workflows/ci-vue.yml [hunk 25]
```diff
@@ -3,12 +3,12 @@ name: CI for vue package
 on:
   push:
     paths:
-      - "packages/vue-vocabulary/**"
+      - "scripts/**"
```
Comment (brylie) [inline .github/workflows/ci-vue.yml]: Revert
```suggestion
      - "packages/vue-vocabulary/**"
```

File: .github/workflows/ci-vue.yml [hunk 26]
```diff
@@ -3,12 +3,12 @@ name: CI for vue package
...
     branches:
       - main
   pull_request:
     paths:
-      - "packages/vue-vocabulary/**"
+      - "scripts/**"
```
Comment (brylie) [inline .github/workflows/ci-vue.yml]: Revert
```suggestion
      - "packages/vue-vocabulary/**"
```

File: .github/workflows/ci-vue.yml [hunk 27]
```diff
@@ -21,7 +21,7 @@ jobs:
     name: Setup
     defaults:
       run:
-        working-directory: "packages/vue-vocabulary"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/ci-vue.yml]: Revert
```suggestion
        working-directory: "packages/vue-vocabulary"
```

File: .github/workflows/ci-vue.yml [hunk 28]
```diff
@@ -46,7 +46,7 @@ jobs:
     name: Lint
     defaults:
       run:
-        working-directory: "packages/vue-vocabulary"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/ci-vue.yml]: Revert
```suggestion
        working-directory: "packages/vue-vocabulary"
```

File: .github/workflows/ci-vue.yml [hunk 29]
```diff
@@ -71,40 +71,11 @@ jobs:
...
-        with:
-          path: ~/.npm # npm caches files in ~/.npm
-          key: node-${{ hashFiles('**/package-lock.json') }}
-
-      - name: Install dependencies
-        run: npm install --prefer-offline --no-audit
-
-      - name: Run tests
-        run: npm run test:unit
-
```
Comment (brylie) [inline .github/workflows/ci-vue.yml]: Revert

File: .github/workflows/ci-vue.yml [hunk 30]
```diff
@@ -71,40 +71,11 @@ jobs:
...
   build:
     name: Build
     defaults:
       run:
-        working-directory: "packages/vue-vocabulary"
+        working-directory: "/"
```
Comment (brylie) [inline .github/workflows/ci-vue.yml]: Revert
```suggestion
        working-directory: "packages/vue-vocabulary"
```

File: .github/workflows/ci-vue.yml [hunk 31]
```diff
@@ -127,4 +98,4 @@ jobs:
         run: npm install --prefer-offline --no-audit
 
       - name: Run build
-        run: npm run build
+        run: npm run build:vue-vocabulary
```
Comment (brylie) [inline .github/workflows/ci-vue.yml]: Revert
```suggestion
        run: npm run build
```

**Review by brylie — CHANGES_REQUESTED** [review]

**Comment by brylie** [comment]
@MuluhGodson, as far as possible, I've gone through and flagged code to be reverted with suggestions. That way, you can click "Commit suggestion" or "add suggestion to batch" in order to easily make the suggested changes. However, there are some deleted blocks of code that will need to be manually restored. They shouldn't be deleted in this or any other issue, as we just need to fix them to work correctly.

**Comment by MuluhGodson** [comment]
@brylie That was very helpful. I noticed it was the last commit I made. So I reverted the commit.

**Review by brylie — APPROVED** [review]

**Comment by emmaxy07** [comment]
npm run build:fonts --fix command still returning previous error on windows

**Comment by MuluhGodson** [comment]
@emmaxy07 
Did you install all the dependencies: 
`npm install --legacy-peer-deps`

The fix above I tested it on two different windows setups (where it previously failed before the fix) and it worked before I opened the PR. 
The npm version on the windows setup is `8.0.0.0` and the node version is `v16.11.0`

I want to emphasize that Prior to this fix the scripts didn't run, but now they do.

**Comment by emmaxy07** [comment]
I just installed all the dependencies with
npm install --legacy-peer-deps

**Comment by emmaxy07** [comment]
npm run build:fonts is still not working

**Comment by brylie** [comment]
@emmaxy07 what error are you getting? What are your versions of npm and node? `npm --version` and `node --version`

**Comment by MuluhGodson** [comment]
@brylie The errors @emmaxy07 and @Akpjunior94 were facing were already resolved. They just had to `git pull`.
